sudo: required

services:
  - docker
# Enable C++ support
language: cpp
# Define cache
cache:
  directories:
  - /home/travis/build/JoHeinrich/amos-ss16-proj5/protobuf-2.6.1
  - /home/travis/build/JoHeinrich/amos-ss16-proj5/actor-framework
# Compiler selection
compiler:
  - gcc
# Install dependencies
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 1397BC53640DB551
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-serial-dev libhdf5-dev libprotobuf8 hdf5-tools
  - sudo apt-get install -y cmake git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev
  - sudo apt-get install -y libdc1394-22-dev
  - sudo apt-get install -y doxygen graphviz #for docugeneration
#  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
#  - tar xzf protobuf-2.6.1.tar.gz
  - cd protobuf-2.6.1
#  - ./configure
#  - make
#  - make check
  - sudo make install
  - sudo ldconfig
  - cd ..
# Install CAF
#  - git clone https://github.com/actor-framework/actor-framework.git
  - cd actor-framework
#  - ./configure
#  - make
#  - make test
  - sudo make install
  - cd ..
before_script:
  - export OpenCV_DIR=/home/travis/build/JoHeinrich/amos-ss16-proj5/docker/assets/openCV/share/OpenCV/
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - cd ..
  - doxygen
  - docker/build
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull amosproj5/amosbuildimage:v1
  - docker build -t amosproj5/amosbuildimage:v1 docker/
  - docker push amosproj5/amosbuildimage:v1

after_success:
#cd "$TRAVIS_BUILD_DIR"
# This generates a `web` directory containing the website.
# make web
  - cd html
  - git init
  - git checkout -b gh-pages
  - git add .
  - git -c user.name='travis' -c user.email='travis' commit -m init
# Make sure to make the output quiet, or else the API token will leak!
# This works because the API key can replace your password.
  - git push -f -q https://joheinrich:$GITHUB_API_KEY@github.com/joheinrich/amos-ss16-proj5-gh-pages gh-pages &2>/dev/null
#cd "$TRAVIS_BUILD_DIR
