sudo: required

services:
  - docker
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - gcc
# Install dependencies
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 1397BC53640DB551
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-serial-dev libhdf5-dev libprotobuf8 hdf5-tools
  - wget https://github.com/google/protobuf/releases/download/v2.6.1/protobuf-2.6.1.tar.gz
  - tar xzf protobuf-2.6.1.tar.gz
  - cd protobuf-2.6.1
  - ./configure
  - make
  - make check
  - sudo make install
  - sudo ldconfig
  - cd ..
before_script:
  - export OpenCV_DIR=/home/travis/build/JoHeinrich/amos-ss16-proj5/docker/assets/openCV/share/OpenCV/
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - cd ..
  - docker/build
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull amosproj5/amosbuildimage:v1
  - docker build -t amosproj5/amosbuildimage:v1 docker/
  - docker push amosproj5/amosbuildimage:v1

