sudo: required

services:
  - docker
# Enable C++ support
language: cpp
# Compiler selection
compiler:
  - clang
  - gcc
# Install dependencies
  - sudo apt-get -qq update
  - sudo apt-get install -y libhdf5-cpp-11 hdf5-tools libprotobuf9v5
# Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
  - cd ..
  - docker/build
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker pull amosproj5/amosbuildimage:v1
  - docker build -t amosproj5/amosbuildimage:v1 docker/
  - docker push amosproj5/amosbuildimage:v1

