#!/bin/bash
set -ue
# This script is always executed in the **root** of your repository

echo
echo "Copying final artifact to docker assets directory"
mkdir -p docker/assets/bin
cp -v -r build/bin ./docker/assets/bin
