#!/bin/bash
set -ue
# This script is always executed in the **root** of your repository

echo
echo "Copying final artifact to docker assets directory"
rm -rf ./docker/assets/AutoDrive
mkdir -p ./docker/assets
cp -v ./AutoDrive ./docker/assets/AutoDrive 
